name: PingMonitor
options:
  bundleIdPrefix: com.pingmonitor
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "17.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "2.0.52"
    CURRENT_PROJECT_VERSION: "53"

targets:
  PingMonitor:
    type: application
    platform: macOS
    sources:
      - path: PingMonitor
      - path: PingMonitor/HostDetailView.swift
      - path: PingMonitor/TracerouteManager.swift
      - path: PingMonitor/TracerouteView.swift
      - path: PingMonitor/WidgetDataManager.swift
    settings:
      base:
        INFOPLIST_FILE: PingMonitor/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.pingmonitor.app
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: PingMonitor/PingMonitor.entitlements
    entitlements:
      path: PingMonitor/PingMonitor.entitlements
      properties:
        # com.apple.security.application-groups:
        #   - group.com.pingmonitor.shared
    dependencies:
      - target: PingMonitorWidget
        embed: true

  PingMonitorWidget:
    type: app-extension
    platform: macOS
    sources:
      - path: PingMonitorWidget
      - path: PingMonitor/WidgetDataManager.swift
    settings:
      base:
        INFOPLIST_FILE: PingMonitorWidget/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.pingmonitor.app.widget
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: NO
        SKIP_INSTALL: NO
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    entitlements:
      path: PingMonitorWidget/PingMonitorWidget.entitlements
      properties:
        # com.apple.security.application-groups:
        #   - group.com.pingmonitor.shared
        com.apple.security.app-sandbox: true
