import SwiftUI

enum Language: String, CaseIterable {
    case zh = "zh"
    case en = "en"
    
    var displayName: String {
        switch self {
        case .zh: return "中文"
        case .en: return "English"
        }
    }
}

@MainActor
public final class LanguageManager: ObservableObject {
    public static let shared = LanguageManager()
    
    @AppStorage("appLanguage", store: UserDefaults(suiteName: "group.com.pingmonitor.shared")) var languageString: String = "zh" {
        didSet {
            currentLanguage = Language(rawValue: languageString) ?? .zh
        }
    }
    
    @Published var currentLanguage: Language = .zh
    
    init() {
        self.currentLanguage = Language(rawValue: languageString) ?? .zh
    }
    
    func t(_ key: String) -> String {
        return translations[currentLanguage]?[key] ?? key
    }
    
    func toggle() {
        languageString = (currentLanguage == .zh) ? "en" : "zh"
    }
    
    // MARK: - Translations
    private let translations: [Language: [String: String]] = [
        .en: [
            // Sidebar
            "sidebar.monitor": "Monitor",
            "sidebar.dashboard": "Dashboard",
            "sidebar.traceroute": "Traceroute",
            "sidebar.hosts": "Hosts",
            "sidebar.logs": "Logs",
            "sidebar.settings": "Settings",
            "sidebar.overview": "Overview",
            "sidebar.management": "Management",
            "sidebar.config": "Config",
            "sidebar.admin": "Administrator",
            
            // Header
            "header.monitoring": "Monitoring %d hosts",
            "header.stopped": "Stopped",
            "header.start": "Start",
            "header.stop": "Stop",
            
            // Dashboard
            "dashboard.running_status": "Running Status",
            "dashboard.uptime": "Uptime",
            "dashboard.running": "Running",
            "dashboard.hosts_count": "Hosts",
            "dashboard.memory": "Memory",
            "dashboard.system": "System",
            "dashboard.version": "Version",
            "dashboard.network_status": "Network Status",
            "dashboard.network_wifi": "Network",
            "dashboard.latency_trend": "Latency Trend",
            "dashboard.no_data": "No Data",
            "dashboard.quality_score": "Quality Score",
            "dashboard.health_window": "Evaluate network quality across the selected time window",
            "dashboard.window_1m": "1m",
            "dashboard.window_5m": "5m",
            "dashboard.window_1h": "1h",
            "dashboard.p95_latency": "P95 Latency",
            "dashboard.avg_loss": "Avg Loss",
            "dashboard.avg_jitter": "Avg Jitter",
            "dashboard.healthy_hosts": "Healthy",
            "dashboard.degraded_hosts": "Degraded",
            "dashboard.critical_hosts": "Critical",
            "dashboard.dimension_breakdown": "Dimension Breakdown",
            "dashboard.path_health": "Path Health",
            "dashboard.bandwidth_pressure": "Bandwidth Pressure",
            "dashboard.resolution": "Resolution",
            "dashboard.overlay": "Overlay",
            "dashboard.recent_events": "Recent Events",
            "dashboard.no_events": "No recent anomalies",
            "dashboard.host_health": "Host Health",
            "dashboard.tunnel_ratio": "Tunnel Ratio",
            "dashboard.samples": "Trend",
            "dashboard.top_consumer": "Top Consumer",
            "dashboard.physical_traffic": "Physical Traffic",
            "dashboard.tunnel_traffic": "Tunnel Traffic",
            "dashboard.seven_day_trend": "7-Day Trend",
            "dashboard.daily_avg": "Daily Avg",
            "dashboard.ping_summary": "Ping Summary",
            "dashboard.total": "Total",
            "dashboard.success": "Success",
            "dashboard.failed": "Failed",
            "dashboard.timeout": "Timeout",
            "dashboard.latency_ranking": "Latency Ranking",
            
            // Monitor Tab
            "monitor.title": "Monitoring Hosts",
            "monitor.add": "Add",
            "monitor.no_hosts": "No Hosts",
            "monitor.add_host_hint": "Click add button to start",
            "monitor.quick_access": "Quick Access",
            "monitor.quick_access_hint": "Group service shortcuts by host for faster daily operations",
            "monitor.quick_access_hosts": "Hosts",
            "monitor.quick_access_services": "Services",
            "monitor.quick_access_open": "Open",
            "monitor.quick_access_copy": "Copy Target",
            
            // Host Management
            "host.manage.section.saved": "Saved Hosts",
            "host.manage.section.presets": "Presets",
            "host.manage.add": "Add Host",
            "host.manage.no_hosts": "No Hosts",
            "host.manage.add_hint": "Add host to start monitoring",
            "host.manage.quick_add": "Quick Add Presets",
            "host.manage.add_preset": "Add Preset",
            "host.manage.no_presets": "No Presets",
            "host.manage.add_preset_hint": "Add presets for quick host creation",
            
            // Editors
            "editor.add_host": "Add Host",
            "editor.edit_host": "Edit Host",
            "editor.add_preset": "Add Preset",
            "editor.edit_preset": "Edit Preset",
            "editor.basic_info": "Basic Info",
            "editor.name": "Name",
            "editor.address": "Address",
            "editor.command": "Command (Optional)",
            "editor.command_hint": "Default: ping -i 10 $address\nSupports $address placeholder",
            "editor.preset_command_hint": "Default: ping -c 1 -W 3 $address",
            "editor.display_rules": "Display Rules",
            "editor.add_rule": "Add Rule",
            "editor.cancel": "Cancel",
            "editor.save": "Save",
            "editor.add": "Add",
            
            // Common
            "common.add": "Add",
            "common.cancel": "Cancel",
            "common.save": "Save",
            "common.back": "Back",
            
            // Editor sections
            "editor.section.basic": "Basic Info",
            "editor.section.rules": "Display Rules",
            
            // Editor rule aliases (code uses editor.rule.* prefix)
            "editor.rule.enable": "Enable",
            "editor.rule.condition": "Condition",
            "editor.rule.greater": "Greater than",
            "editor.rule.less": "Less than",
            "editor.rule.threshold": "Threshold (ms)",
            "editor.rule.label": "Label",
            "editor.rule.label_placeholder": "e.g. P2P",
            
            // Rules
            "rule.enable": "Enable",
            "rule.condition": "Condition",
            "rule.less": "Less than",
            "rule.greater": "Greater than",
            "rule.threshold": "Threshold (ms)",
            "rule.label": "Label",
            "rule.add_title": "Add Display Rule",
            "rule.latency_less": "Latency <",
            "rule.latency_greater": "Latency >",
            
            // Logs
            "logs.level": "Log Level",
            "logs.level.all": "All",
            "logs.level.debug": "DEBUG",
            "logs.level.info": "INFO",
            "logs.level.warn": "WARN",
            "logs.level.error": "ERROR",
            "logs.all": "All",
            "logs.clear": "Clear",
            "logs.export": "Export",
            
            // Settings
            "settings.display_mode": "Display Mode",
            "settings.display.average": "Average",
            "settings.display.worst": "Worst",
            "settings.display.best": "Best",
            "settings.display.first": "First",
            "settings.avg_latency": "Avg Latency",
            "settings.worst_host": "Worst Host",
            "settings.best_host": "Best Host",
            "settings.first_host": "First Host",
            "settings.desc.average": "Show average latency of all hosts",
            "settings.desc.worst": "Show highest latency or unreachable host",
            "settings.desc.best": "Show lowest latency host",
            "settings.desc.first": "Show first host in the list",
            "settings.desc.avg": "Show average latency of all hosts",
            "settings.desc.worst_old": "Show highest latency or unreachable",
            "settings.desc.best_old": "Show lowest latency",
            "settings.desc.first_old": "Show first host in list",
            "settings.show_latency": "Show Latency Value",
            "settings.show_labels": "Show Rule Labels",
            "settings.show_speed": "Show Network Speed",
            "settings.speed_unit": "Speed Unit",
            "settings.speed_unit.auto": "Auto",
            "settings.bar_width": "Status Bar Width",
            "settings.icon_width": "Icon Width",
            "settings.latency_width": "Latency Width",
            "settings.label_width": "Label Width",
            "settings.speed_width": "Speed Width",
            "settings.font_size": "Font Size",
            "settings.font_weight": "Font Weight",
            "settings.font_weight.regular": "Regular",
            "settings.font_weight.medium": "Medium",
            "settings.font_weight.bold": "Bold",
            "settings.status_bar": "Status Bar",
            "settings.show_icon": "Show Icon",
            "settings.section.status_bar": "Status Bar",
            "settings.section.monitor": "Monitor",
            "settings.section.notify": "Notification",
            "settings.section.system": "System",
            "settings.interval": "Ping Interval",
            "settings.interval.3s": "3s",
            "settings.interval.5s": "5s",
            "settings.interval.10s": "10s",
            "settings.interval.15s": "15s",
            "settings.interval.30s": "30s",
            "settings.monitor_interval": "Monitor Interval",
            "settings.seconds": "%.0fs",
            "settings.monitor": "Monitor",
            "settings.notify.enable": "Enable Notification",
            "settings.notify.type": "Notification Type",
            "settings.enable_notify": "Enable Notification",
            "settings.notify_type": "Notification Type",
            "settings.notify.system": "System",
            "settings.notify.bark": "Bark",
            "settings.notify": "Notification",
            "settings.auto_start": "Launch at Login",
            "settings.tailscale": "Tailscale",
            "settings.tailscale.help": "Show Tailscale features. Requires the Tailscale CLI to be installed and running.",
            "settings.autostart": "Auto Start",
            "settings.system": "System",
            "settings.language": "Language",
            "settings.version": "Version",
            "settings.appearance": "Appearance",
            "settings.appearance.system": "System Default",
            "settings.appearance.light": "Light",
            "settings.appearance.dark": "Dark",
            
            
            
            // Widget Settings
            "settings.widget.mode": "Widget Mode",
            "settings.widget.none": "None",
            "settings.widget.auto": "Auto (Top 5)",
            "settings.widget.specific": "Specific Host",
            "settings.widget.select_host": "Select Host",
            
            // Stats Details
            "stats.quality_assessment": "Quality Assessment",
            "stats.dimension_readability": "Read score, dimensions, rules, and anomalies in one screen",
            "stats.dimension_scores": "Dimension Scores",
            "stats.quality_trend": "Quality Trend",
            "stats.recent_anomalies": "Recent Anomalies",
            "stats.no_events": "No recent anomalies",
            "stats.scoring_standard": "Scoring Standards",
            "stats.scoring_hint": "Weights and thresholds used by the current quality model",
            "stats.current_score_hint": "Weighted by latency, stability, path, bandwidth, resolution, and overlay",
            "stats.availability": "Availability",
            "stats.current_path": "Current Path",
            "stats.path_flaps": "Path Flaps",
            "stats.consecutive_failures": "Consecutive Fails",
            "stats.raw_metrics": "Raw Metrics",
            "stats.worst_hosts": "Risk Hosts",
            "stats.window": "Window",
            "stats.grade.excellent": "Excellent",
            "stats.grade.good": "Good",
            "stats.grade.fair": "Fair",
            "stats.grade.poor": "Poor",
            "stats.grade.critical": "Critical",
            "stats.dimension.latency": "Latency",
            "stats.dimension.stability": "Stability",
            "stats.dimension.path": "Path",
            "stats.dimension.bandwidth": "Bandwidth",
            "stats.dimension.resolution": "Resolution",
            "stats.dimension.overlay": "Overlay",
            "stats.standard.latency.signal": "Signals: p95, jitter, spike rate",
            "stats.standard.latency.rule": "Excellent under 50ms. Large p95 spikes and jitter quickly reduce the score.",
            "stats.standard.stability.signal": "Signals: availability, packet loss, consecutive failures",
            "stats.standard.stability.rule": "Availability below 97% or repeated failures sharply lowers stability.",
            "stats.standard.path.signal": "Signals: direct/relay, route errors, path switches",
            "stats.standard.path.rule": "Direct paths score highest. Relay and frequent path changes are penalized.",
            "stats.standard.bandwidth.signal": "Signals: physical/tunnel throughput, pressure correlation",
            "stats.standard.bandwidth.rule": "High sustained traffic or tunnel-heavy traffic lowers this score when quality degrades at the same time.",
            "stats.standard.resolution.signal": "Signals: DNS failures and resolution dependency",
            "stats.standard.resolution.rule": "Hosts that depend on DNS are penalized immediately when resolution starts failing.",
            "stats.standard.overlay.signal": "Signals: Tailscale direct/relay condition and overlay health",
            "stats.standard.overlay.rule": "Direct overlay paths score higher than relay-heavy or degraded overlay routes.",
            "stats.detailed": "Detailed Stats",
            "stats.requests": "Requests",
            "stats.success_rate": "Success Rate",
            "stats.loss_rate": "Loss Rate",
            "stats.traffic": "Traffic",
            "stats.success": "Success",
            "stats.failed": "Failed",
            "stats.min_latency": "Min Latency",
            "stats.max_latency": "Max Latency",
            "stats.avg_latency": "Avg Latency",
            "stats.sent": "Sent",
            "stats.received": "Received",
            "stats.export_current": "Export Current",
            "stats.export_all": "Export All",
            "stats.reset_current": "Reset Current",
            "stats.reset_all": "Reset All",
            "stats.time.hours": "%dh %dm",
            "stats.time.minutes": "%dm %ds",
            "stats.time.seconds": "%ds",
            "stats.legend.excellent": "<50ms Excellent",
            "stats.legend.good": "<100ms Good",
            "stats.legend.poor": ">100ms Poor",
            "stats.chart.count": "Count %d",
            "stats.chart.current": "Current",
            "stats.select_host": "Select Host",
            "stats.all_hosts": "All Hosts",
            
            // Cards
            "card.rules": "%d Rules",
            "card.timeout": "Timeout",
            "card.score": "Score",
            "card.p95": "P95",
            "card.loss": "Loss",
            "card.path": "Path",
            "card.services": "Services",
            "card.measuring": "Measuring",
            "card.score_help": "Quality score (0–100). Computed from latency, stability, path, bandwidth, resolution, and overlay over the last 5 minutes.",
            
            // Diagnostics
            "diagnostics.result.reachable": "Reachable",
            "diagnostics.failure.timeout": "Timeout",
            "diagnostics.failure.dns": "DNS failed",
            "diagnostics.failure.no_route": "No route to host",
            "diagnostics.failure.network_unreachable": "Network unreachable",
            "diagnostics.failure.host_down": "Host down",
            "diagnostics.failure.connection_refused": "Connection refused",
            "diagnostics.failure.permission_denied": "Permission denied",
            "diagnostics.failure.process_error": "Probe error",
            "diagnostics.failure.unknown": "Unknown error",
            "diagnostics.path.direct": "Direct",
            "diagnostics.path.direct_via": "Direct via %@",
            "diagnostics.path.relay": "Relay",
            "diagnostics.path.relay_via": "Relay via %@",
            "diagnostics.path.unknown": "Path unknown",
            "quality_event.path_relay": "Path switched to relay",
            "quality_event.path_updated": "Path updated",
            "quality_event.host_recovered": "Host recovered",
            "quality_event.host_recovered_detail": "Probe responses are healthy again",
            "quality_event.probe_failed": "Probe failed",
            "quality_event.score_critical": "Quality dropped to critical",
            "quality_event.score_critical_detail": "Score fell from %d to %d (below threshold 40)",
            "quality_event.score_degraded": "Quality degraded",
            "quality_event.score_degraded_detail": "Score dropped from %d to %d",

            // Context Menu
            "menu.edit": "Edit",
            "menu.delete": "Delete",
            "menu.add_to_monitor": "Add to Monitor",
            
            // Traceroute
            "traceroute.title": "Route Tracing",
            "traceroute.input_placeholder": "Enter hostname or IP",
            "traceroute.start": "Start Trace",
            "traceroute.stop": "Stop",
            "traceroute.mtr_mode": "MTR Mode",
            "traceroute.hop": "Hop",
            "traceroute.ip": "IP / Host",
            "traceroute.latency": "Latency",
            "traceroute.avg": "Avg",
            "traceroute.loss": "Loss",
            "traceroute.status": "Status",
            "traceroute.tracing": "Tracing route to %@...",
            "traceroute.complete": "Trace complete: %d hops",
            "traceroute.no_result": "No results yet",
            "traceroute.hint": "Enter a target to trace its network route",
            "traceroute.copy": "Copy Result",
            "traceroute.copied": "Copied!",
            "traceroute.timeout": "Timeout",
            "traceroute.mtr_hint": "MTR combines ping and traceroute for continuous monitoring",
            "traceroute.monitored_hosts": "Monitored Hosts",
            "traceroute.your_location": "Your Location",
            "traceroute.local_interface": "Local Interface",
            "traceroute.source": "Source",
            "traceroute.interface": "Interface",
            "traceroute.gateway": "Gateway",
            "traceroute.nslookup": "NSLookup",
            "traceroute.nslookup_server": "DNS Server",
            "traceroute.nslookup_empty": "Run NSLookup to inspect DNS answers",
            "traceroute.lookup_failed": "NSLookup failed",
            
            // Host Detail
            "host_detail.checking": "Checking...",
            "host_detail.connection_status": "Connection Status",
            "host_detail.status": "Status",
            "host_detail.online": "Online",
            "host_detail.offline": "Offline",
            "host_detail.uptime": "Uptime",
            "host_detail.latency_stats": "Latency Statistics",
            "host_detail.current": "Current",
            "host_detail.min": "Min",
            "host_detail.max": "Max",
            "host_detail.avg": "Average",
            "host_detail.jitter": "Jitter",
            "host_detail.latency_chart": "Real-time Latency",
            "host_detail.data_points": "Points",
            "host_detail.packet_stats": "Packet Statistics",
            "host_detail.total_pings": "Total Pings",
            "host_detail.success": "Success",
            "host_detail.failed": "Failed",
            "host_detail.success_rate": "Success Rate",
            "host_detail.traffic": "Traffic",
            "host_detail.sent": "Sent",
            "host_detail.received": "Received",
            "host_detail.total_traffic": "Total",
            "host_detail.display_rules": "Display Rules",
            "host_detail.enabled": "Enabled",
            "host_detail.disabled": "Disabled",
            "host_detail.probe_mode": "Probe",
            "host_detail.last_result": "Last Result",
            "host_detail.path": "Path",
            "host_detail.last_checked": "Last Check",
            "host_detail.command": "Command",
            
            // Tailscale
            "sidebar.tailscale": "Tailscale",
            "sidebar.services": "Services",
            "tailscale.title": "Tailscale Network",
            "tailscale.status": "Status",
            "tailscale.connected": "Connected",
            "tailscale.disconnected": "Disconnected",
            "tailscale.my_ip": "My IP",
            "tailscale.nodes": "Network Nodes",
            "tailscale.refresh": "Refresh",
            "tailscale.import": "Import",
            "tailscale.import_all": "Import All Online",
            "tailscale.online": "Online",
            "tailscale.offline": "Offline",
            "tailscale.self": "This Device",
            "tailscale.already_monitored": "Monitored",
            "tailscale.not_available": "Tailscale is not installed or not running",
            "tailscale.loading": "Loading...",
            "tailscale.netcheck": "Network Check",
            "tailscale.nat_type": "NAT Type",
            "tailscale.preferred_derp": "Preferred DERP",
            "tailscale.derp_latency": "DERP Region Latency",
            "tailscale.captive_portal": "No Portal",
            "tailscale.diagnostics": "Diagnostics",
            "tailscale.path_analysis": "Path Analysis",
            "tailscale.direct": "Direct (P2P)",
            "tailscale.relay": "Relay",
            "tailscale.ping_button": "Path Ping",
            "tailscale.health_report": "Health Report",
            "tailscale.advice.symmetric_nat": "Symmetric NAT detected. P2P may be difficult. Try UPnP or Port Forwarding.",
            "tailscale.advice.easy_nat": "Easy NAT detected. P2P should work well.",
            "tailscale.advice.udp_blocked": "UDP is blocked. P2P is impossible. Check firewall.",
            "tailscale.advice.captive_portal": "Captive portal detected. This may interfere with connections.",
            
            // Services
            "services.title": "Service Shortcuts",
            "services.all": "All",
            "services.add": "Add",
            "services.edit": "Edit Shortcut",
            "services.select_host": "Target Host",
            "services.empty": "No service shortcuts",
            "services.empty_hint": "Add shortcuts in host details",
            "services.name": "Name",
            "services.url": "URL / Address",
            "services.icon": "Icon",
            "services.type": "Type",
            "services.type.web": "Web",
            "services.type.ssh": "SSH",
            "services.type.custom": "Custom",
            "services.ssh.host": "Host Address",
            "services.ssh.user": "Username",
            "services.ssh.port": "Port",
            "services.ssh.key": "Key Path",
            "services.ssh.key_optional": "optional",
            "services.ssh.auth_mode": "Auth Mode",
            "services.ssh.auth_key": "🔑 Key",
            "services.ssh.auth_password": "🔒 Password",
            "services.ssh.password": "Password",
            "services.ssh.password_hint": "Enter password",
            "services.open": "Open",
            "services.ssh.preview": "Command Preview",
            
            // Network Speed
            "sidebar.netspeed": "Net Speed",
            "netspeed.title": "Real-time Network Speed",
            "netspeed.upload": "Upload",
            "netspeed.download": "Download",
            "netspeed.all_interfaces": "All Interfaces",
            "netspeed.realtime_chart": "Real-time Chart",
            "netspeed.collecting": "Collecting data...",
            "netspeed.last_60s": "Last 60s",
            "netspeed.interfaces": "Network Interfaces",
            "netspeed.no_interfaces": "No interfaces detected",
            "netspeed.traffic_stats": "Traffic Statistics",
            "netspeed.total_download": "Total Download",
            "netspeed.total_upload": "Total Upload",
            "netspeed.total_traffic": "Total Traffic",
            "netspeed.traffic_trend": "Traffic Trend",
            "netspeed.tab.interfaces": "Interfaces",
            "netspeed.tab.processes": "Processes",
            "netspeed.process.name": "Process",
            "netspeed.process.pid": "PID",
            "netspeed.process.connections": "Conn",
            "netspeed.process.protocol": "Protocol",
            "netspeed.process.local": "Local",
            "netspeed.process.remote": "Remote",
            "netspeed.process.state": "State",
            "netspeed.process.port": "Port",
            "netspeed.process.kill": "Terminate",
            "netspeed.process.kill_confirm": "Terminate \"%@\" (PID %d)?",
            "netspeed.process.kill_success": "Process terminated",
            "netspeed.process.kill_failed": "Failed to terminate",
            "netspeed.process.search": "Search processes...",
            "netspeed.process.no_connections": "No active connections",
            "netspeed.process.refresh": "Refresh",
            "netspeed.top_processes": "Top Processes",
            "netspeed.process.speed": "Speed",
            
            // Logs (additions)
            "logs.title": "Logs",
            "logs.empty": "No logs yet",
        ],
        .zh: [
            // Sidebar
            "sidebar.monitor": "监控",
            "sidebar.dashboard": "统计",
            "sidebar.traceroute": "路由追踪",
            "sidebar.hosts": "主机管理",
            "sidebar.logs": "日志",
            "sidebar.settings": "设置",
            "sidebar.overview": "概览",
            "sidebar.management": "管理",
            "sidebar.config": "配置",
            "sidebar.admin": "管理员",
            
            // Header
            "header.monitoring": "正在监控 %d 个主机",
            "header.stopped": "已停止",
            "header.start": "开始",
            "header.stop": "停止",
            
            // Dashboard
            "dashboard.running_status": "运行状态",
            "dashboard.uptime": "运行时间",
            "dashboard.running": "运行中",
            "dashboard.hosts_count": "主机数量",
            "dashboard.memory": "内存占用",
            "dashboard.system": "系统",
            "dashboard.version": "版本",
            "dashboard.network_status": "网络状态",
            "dashboard.network_wifi": "网络连接",
            "dashboard.latency_trend": "延迟趋势",
            "dashboard.no_data": "暂无数据",
            "dashboard.quality_score": "质量分",
            "dashboard.health_window": "按选定时间窗口评估当前网络质量",
            "dashboard.window_1m": "1分",
            "dashboard.window_5m": "5分",
            "dashboard.window_1h": "1小时",
            "dashboard.p95_latency": "P95 延迟",
            "dashboard.avg_loss": "平均丢包",
            "dashboard.avg_jitter": "平均抖动",
            "dashboard.healthy_hosts": "健康",
            "dashboard.degraded_hosts": "降级",
            "dashboard.critical_hosts": "严重",
            "dashboard.dimension_breakdown": "维度拆解",
            "dashboard.path_health": "路径健康",
            "dashboard.bandwidth_pressure": "带宽压力",
            "dashboard.resolution": "解析",
            "dashboard.overlay": "Overlay",
            "dashboard.recent_events": "最近异常",
            "dashboard.no_events": "最近没有异常事件",
            "dashboard.host_health": "主机健康矩阵",
            "dashboard.tunnel_ratio": "隧道占比",
            "dashboard.samples": "趋势",
            "dashboard.top_consumer": "流量最高进程",
            "dashboard.physical_traffic": "物理流量",
            "dashboard.tunnel_traffic": "隧道流量",
            "dashboard.seven_day_trend": "7日趋势",
            "dashboard.daily_avg": "日平均",
            "dashboard.ping_summary": "Ping 统计",
            "dashboard.total": "总计",
            "dashboard.success": "成功",
            "dashboard.failed": "失败",
            "dashboard.timeout": "超时",
            "dashboard.latency_ranking": "延迟排行",
            
            // Monitor Tab
            "monitor.title": "监控中主机",
            "monitor.add": "添加",
            "monitor.no_hosts": "没有主机",
            "monitor.add_host_hint": "点击右上角按钮添加主机",
            "monitor.quick_access": "快速入口",
            "monitor.quick_access_hint": "按主机分组展示服务快捷方式，便于日常高频操作",
            "monitor.quick_access_hosts": "主机",
            "monitor.quick_access_services": "服务",
            "monitor.quick_access_open": "打开",
            "monitor.quick_access_copy": "复制目标",
            
            // Host Management
            "host.manage.section.saved": "已保存主机",
            "host.manage.section.presets": "预设",
            "host.manage.add": "添加主机",
            "host.manage.no_hosts": "没有主机",
            "host.manage.add_hint": "添加主机开始监控",
            "host.manage.quick_add": "预设快速添加",
            "host.manage.add_preset": "添加预设",
            "host.manage.no_presets": "没有预设",
            "host.manage.add_preset_hint": "添加预设快速创建主机",
            
            // Editors
            "editor.add_host": "添加主机",
            "editor.edit_host": "编辑主机",
            "editor.add_preset": "添加预设",
            "editor.edit_preset": "编辑预设",
            "editor.basic_info": "基本信息",
            "editor.name": "名称",
            "editor.address": "地址",
            "editor.command": "命令 (可选)",
            "editor.command_hint": "留空默认: ping -i 10 $address\n支持 $address 占位符",
            "editor.preset_command_hint": "留空默认: ping -c 1 -W 3 $address",
            "editor.display_rules": "显示规则",
            "editor.add_rule": "添加规则",
            "editor.cancel": "取消",
            "editor.save": "保存",
            "editor.add": "添加",
            
            // Common
            "common.add": "添加",
            "common.cancel": "取消",
            "common.save": "保存",
            "common.back": "返回",
            
            // Editor sections
            "editor.section.basic": "基本信息",
            "editor.section.rules": "显示规则",
            
            // Editor rule aliases
            "editor.rule.enable": "启用",
            "editor.rule.condition": "条件",
            "editor.rule.greater": "> 大于",
            "editor.rule.less": "< 小于",
            "editor.rule.threshold": "阈值(ms)",
            "editor.rule.label": "显示文本",
            "editor.rule.label_placeholder": "如: P2P",
            
            // Rules
            "rule.enable": "启用",
            "rule.condition": "条件",
            "rule.less": "< 小于",
            "rule.greater": "> 大于",
            "rule.threshold": "阈值(ms)",
            "rule.label": "显示文本",
            "rule.add_title": "添加显示规则",
            "rule.latency_less": "延迟小于",
            "rule.latency_greater": "延迟大于",
            
            // Logs
            "logs.level": "日志级别",
            "logs.level.all": "全部",
            "logs.level.debug": "调试",
            "logs.level.info": "信息",
            "logs.level.warn": "警告",
            "logs.level.error": "错误",
            "logs.all": "全部",
            "logs.clear": "清空",
            "logs.export": "导出",
            
            // Settings
            "settings.display_mode": "显示策略",
            "settings.display.average": "平均值",
            "settings.display.worst": "最差",
            "settings.display.best": "最优",
            "settings.display.first": "首个",
            "settings.avg_latency": "平均延迟",
            "settings.worst_host": "最差主机",
            "settings.best_host": "最快主机",
            "settings.first_host": "首个主机",
            "settings.desc.average": "显示所有主机的平均延迟",
            "settings.desc.worst": "显示延迟最高或不可达的主机",
            "settings.desc.best": "显示延迟最低的主机",
            "settings.desc.first": "显示列表中的第一个主机",
            "settings.desc.avg": "显示所有主机的平均延迟",
            "settings.desc.worst_old": "显示延迟最高或不可达的主机",
            "settings.desc.best_old": "显示延迟最低的主机",
            "settings.desc.first_old": "显示列表中的第一个主机",
            "settings.show_latency": "显示延迟数值",
            "settings.show_labels": "显示规则标签",
            "settings.show_speed": "显示网速",
            "settings.speed_unit": "网速单位",
            "settings.speed_unit.auto": "自动",
            "settings.bar_width": "状态栏宽度",
            "settings.icon_width": "图标宽度",
            "settings.latency_width": "延迟数值宽度",
            "settings.label_width": "规则标签宽度",
            "settings.speed_width": "网速宽度",
            "settings.font_size": "字体大小",
            "settings.font_weight": "字体粗细",
            "settings.font_weight.regular": "常规",
            "settings.font_weight.medium": "中等",
            "settings.font_weight.bold": "加粗",
            "settings.status_bar": "状态栏显示",
            "settings.show_icon": "显示图标",
            "settings.section.status_bar": "状态栏显示",
            "settings.section.monitor": "监控",
            "settings.section.widget": "小组件",
            "settings.section.notify": "通知",
            "settings.section.system": "系统",
            "settings.interval": "Ping 间隔",
            "settings.interval.3s": "3秒",
            "settings.interval.5s": "5秒",
            "settings.interval.10s": "10秒",
            "settings.interval.15s": "15秒",
            "settings.interval.30s": "30秒",
            "settings.monitor_interval": "监控间隔",
            "settings.seconds": "%.0f秒",
            "settings.monitor": "监控",
            "settings.notify.enable": "启用通知",
            "settings.notify.type": "通知方式",
            "settings.enable_notify": "启用通知",
            "settings.notify_type": "通知方式",
            "settings.notify.system": "系统通知",
            "settings.notify.bark": "Bark推送",
            "settings.notify": "通知",
            "settings.auto_start": "开机自启动",
            "settings.tailscale": "Tailscale",
            "settings.tailscale.help": "显示 Tailscale 相关功能。需要已安装并运行 Tailscale CLI。",
            "settings.autostart": "开机自启动",
            "settings.system": "系统",
            "settings.language": "语言",
            "settings.version": "版本",
            "settings.appearance": "外观",
            "settings.appearance.system": "跟随系统",
            "settings.appearance.light": "浅色",
            "settings.appearance.dark": "深色",
            
            
            
            // Widget Settings
            "settings.widget.mode": "小组件模式",
            "settings.widget.none": "无",
            "settings.widget.auto": "自动 (前5个)",
            "settings.widget.specific": "指定主机",
            "settings.widget.select_host": "选择展示主机",
            
            // Stats Details
            "stats.quality_assessment": "质量评估",
            "stats.dimension_readability": "在一屏内查看分数、维度、评分规则和最近异常",
            "stats.dimension_scores": "维度评分",
            "stats.quality_trend": "质量趋势",
            "stats.recent_anomalies": "最近异常",
            "stats.no_events": "最近没有异常",
            "stats.scoring_standard": "评分标准",
            "stats.scoring_hint": "当前质量模型使用的权重与阈值",
            "stats.current_score_hint": "由延迟、稳定性、路径、带宽、解析与 Overlay 六个维度加权得出",
            "stats.availability": "可用率",
            "stats.current_path": "当前路径",
            "stats.path_flaps": "路径抖动",
            "stats.consecutive_failures": "连续失败",
            "stats.raw_metrics": "原始指标",
            "stats.worst_hosts": "风险主机",
            "stats.window": "窗口",
            "stats.grade.excellent": "优秀",
            "stats.grade.good": "良好",
            "stats.grade.fair": "一般",
            "stats.grade.poor": "较差",
            "stats.grade.critical": "严重",
            "stats.dimension.latency": "延迟",
            "stats.dimension.stability": "稳定性",
            "stats.dimension.path": "路径",
            "stats.dimension.bandwidth": "带宽",
            "stats.dimension.resolution": "解析",
            "stats.dimension.overlay": "Overlay",
            "stats.standard.latency.signal": "信号：p95、抖动、尖峰率",
            "stats.standard.latency.rule": "50ms 以下最优，p95 尖峰和抖动越大，分数下降越快。",
            "stats.standard.stability.signal": "信号：可用率、丢包率、连续失败",
            "stats.standard.stability.rule": "可用率低于 97% 或出现连续失败时，稳定性会被明显拉低。",
            "stats.standard.path.signal": "信号：直连/中继、路由错误、路径切换",
            "stats.standard.path.rule": "直连路径得分最高，中继和频繁路径切换会被惩罚。",
            "stats.standard.bandwidth.signal": "信号：物理/隧道吞吐与质量退化关联",
            "stats.standard.bandwidth.rule": "当高吞吐或高隧道占比与质量下降同时出现时，该维度分数会降低。",
            "stats.standard.resolution.signal": "信号：DNS 失败与解析依赖",
            "stats.standard.resolution.rule": "依赖域名的目标在 DNS 失败出现后会立即被扣分。",
            "stats.standard.overlay.signal": "信号：Tailscale 直连/中继状态与 Overlay 健康度",
            "stats.standard.overlay.rule": "直连 Overlay 得分高于依赖中继或整体不稳定的 Overlay 路径。",
            "stats.detailed": "详细统计",
            "stats.requests": "请求数",
            "stats.success_rate": "成功率",
            "stats.loss_rate": "丢包率",
            "stats.traffic": "总流量",
            "stats.success": "成功请求",
            "stats.failed": "失败请求",
            "stats.min_latency": "最小延迟",
            "stats.max_latency": "最大延迟",
            "stats.avg_latency": "平均延迟",
            "stats.sent": "发送流量",
            "stats.received": "接收流量",
            "stats.export_current": "导出当前统计",
            "stats.export_all": "导出所有统计",
            "stats.reset_current": "重置当前主机统计",
            "stats.reset_all": "重置所有统计",
            "stats.time.hours": "%d小时%d分",
            "stats.time.minutes": "%d分%d秒",
            "stats.time.seconds": "%d秒",
            "stats.legend.excellent": "<50ms 优秀",
            "stats.legend.good": "<100ms 良好",
            "stats.legend.poor": ">100ms 较差",
            "stats.chart.count": "共 %d 次",
            "stats.chart.current": "当前",
            "stats.select_host": "选择主机",
            "stats.all_hosts": "全部主机",
            
            // Cards
            "card.rules": "%d 条规则",
            "card.timeout": "超时",
            "card.score": "评分",
            "card.p95": "P95",
            "card.loss": "丢包",
            "card.path": "路径",
            "card.services": "服务",
            "card.measuring": "测量中",
            "card.score_help": "质量评分（0–100），由最近 5 分钟的延迟、稳定性、路径、带宽、解析与 Overlay 六个维度加权得出。",
            
            // Diagnostics
            "diagnostics.result.reachable": "可达",
            "diagnostics.failure.timeout": "连接超时",
            "diagnostics.failure.dns": "DNS 解析失败",
            "diagnostics.failure.no_route": "无可用路由",
            "diagnostics.failure.network_unreachable": "网络不可达",
            "diagnostics.failure.host_down": "目标主机不可用",
            "diagnostics.failure.connection_refused": "连接被拒绝",
            "diagnostics.failure.permission_denied": "权限不足",
            "diagnostics.failure.process_error": "探测异常",
            "diagnostics.failure.unknown": "未知错误",
            "diagnostics.path.direct": "直连",
            "diagnostics.path.direct_via": "直连经由 %@",
            "diagnostics.path.relay": "中继",
            "diagnostics.path.relay_via": "中继经由 %@",
            "diagnostics.path.unknown": "路径未知",
            "quality_event.path_relay": "路径切换到中继",
            "quality_event.path_updated": "路径已更新",
            "quality_event.host_recovered": "主机已恢复",
            "quality_event.host_recovered_detail": "探测结果已恢复正常",
            "quality_event.probe_failed": "探测失败",
            "quality_event.score_critical": "质量降至严重",
            "quality_event.score_critical_detail": "分数从 %d 降至 %d（低于阈值 40）",
            "quality_event.score_degraded": "质量下降",
            "quality_event.score_degraded_detail": "分数从 %d 降至 %d",

            // Context Menu
            "menu.edit": "编辑",
            "menu.delete": "删除",
            "menu.add_to_monitor": "添加到监控",
            
            // Traceroute
            "traceroute.title": "路由追踪",
            "traceroute.input_placeholder": "输入主机名或 IP",
            "traceroute.start": "开始追踪",
            "traceroute.stop": "停止",
            "traceroute.mtr_mode": "MTR 模式",
            "traceroute.hop": "跳数",
            "traceroute.ip": "IP / 主机名",
            "traceroute.latency": "延迟",
            "traceroute.avg": "平均",
            "traceroute.loss": "丢包",
            "traceroute.status": "状态",
            "traceroute.tracing": "正在追踪到 %@ 的路由...",
            "traceroute.complete": "追踪完成：共 %d 跳",
            "traceroute.no_result": "暂无结果",
            "traceroute.hint": "输入目标地址以追踪网络路由",
            "traceroute.copy": "复制结果",
            "traceroute.copied": "已复制！",
            "traceroute.timeout": "超时",
            "traceroute.mtr_hint": "MTR 结合了 Ping 和 Traceroute 进行持续监控",
            "traceroute.monitored_hosts": "监控中的主机",
            "traceroute.your_location": "当前位置",
            "traceroute.local_interface": "本机接口",
            "traceroute.source": "源地址",
            "traceroute.interface": "接口",
            "traceroute.gateway": "网关",
            "traceroute.nslookup": "NSLookup",
            "traceroute.nslookup_server": "DNS 服务器",
            "traceroute.nslookup_empty": "运行 NSLookup 查看 DNS 解析结果",
            "traceroute.lookup_failed": "NSLookup 执行失败",
            
            // Host Detail
            "host_detail.checking": "检测中...",
            "host_detail.connection_status": "连接状态",
            "host_detail.status": "当前状态",
            "host_detail.online": "在线",
            "host_detail.offline": "离线",
            "host_detail.uptime": "持续时间",
            "host_detail.latency_stats": "延迟统计",
            "host_detail.current": "当前",
            "host_detail.min": "最小",
            "host_detail.max": "最大",
            "host_detail.avg": "平均",
            "host_detail.jitter": "抖动",
            "host_detail.latency_chart": "实时延迟",
            "host_detail.data_points": "个数据点",
            "host_detail.packet_stats": "丢包统计",
            "host_detail.total_pings": "总Ping数",
            "host_detail.success": "成功",
            "host_detail.failed": "失败",
            "host_detail.success_rate": "成功率",
            "host_detail.traffic": "网络流量",
            "host_detail.sent": "发送",
            "host_detail.received": "接收",
            "host_detail.total_traffic": "总流量",
            "host_detail.display_rules": "显示规则",
            "host_detail.enabled": "已启用",
            "host_detail.disabled": "已禁用",
            "host_detail.probe_mode": "探测方式",
            "host_detail.last_result": "最近结果",
            "host_detail.path": "当前路径",
            "host_detail.last_checked": "最近检测",
            "host_detail.command": "命令",
            
            // Tailscale
            "sidebar.tailscale": "Tailscale",
            "sidebar.services": "服务",
            "tailscale.title": "Tailscale 网络",
            "tailscale.status": "状态",
            "tailscale.connected": "已连接",
            "tailscale.disconnected": "未连接",
            "tailscale.my_ip": "本机 IP",
            "tailscale.nodes": "网络节点",
            "tailscale.refresh": "刷新",
            "tailscale.import": "导入",
            "tailscale.import_all": "导入全部在线节点",
            "tailscale.online": "在线",
            "tailscale.offline": "离线",
            "tailscale.self": "本设备",
            "tailscale.already_monitored": "监控中",
            "tailscale.not_available": "Tailscale 未安装或未运行",
            "tailscale.loading": "加载中...",
            "tailscale.netcheck": "网络检测",
            "tailscale.nat_type": "NAT 类型",
            "tailscale.preferred_derp": "首选 DERP",
            "tailscale.derp_latency": "DERP 区域延迟",
            "tailscale.captive_portal": "无强制门户",
            "tailscale.diagnostics": "路径诊断",
            "tailscale.path_analysis": "连接路径分析",
            "tailscale.direct": "直连 (P2P)",
            "tailscale.relay": "中转 (Relay)",
            "tailscale.ping_button": "诊断路径",
            "tailscale.health_report": "网络健康报告",
            "tailscale.advice.symmetric_nat": "检测到对称型 NAT。P2P 建立可能较困难，建议尝试开启 UPnP 或配置端口转发。",
            "tailscale.advice.easy_nat": "检测到全锥型/受限锥型 NAT。P2P 连接应当非常顺畅。",
            "tailscale.advice.udp_blocked": "UDP 协议被拦截。无法建立 P2P 连接，请检查防火墙设置。",
            "tailscale.advice.captive_portal": "检测到网络认证门户（Captive Portal）。这可能会干扰 Tailscale 连接。",
            
            // Services
            "services.title": "服务快捷方式",
            "services.all": "全部",
            "services.add": "添加",
            "services.edit": "编辑快捷方式",
            "services.select_host": "目标主机",
            "services.empty": "暂无服务快捷方式",
            "services.empty_hint": "在主机详情中添加快捷方式",
            "services.name": "名称",
            "services.url": "地址",
            "services.icon": "图标",
            "services.type": "类型",
            "services.type.web": "网页",
            "services.type.ssh": "SSH",
            "services.type.custom": "自定义",
            "services.ssh.host": "主机地址",
            "services.ssh.user": "用户名",
            "services.ssh.port": "端口",
            "services.ssh.key": "密钥路径",
            "services.ssh.key_optional": "可选",
            "services.ssh.auth_mode": "认证方式",
            "services.ssh.auth_key": "🔑 密钥",
            "services.ssh.auth_password": "🔒 密码",
            "services.ssh.password": "密码",
            "services.ssh.password_hint": "输入密码",
            "services.open": "打开",
            "services.ssh.preview": "命令预览",
            
            // Network Speed
            "sidebar.netspeed": "网速",
            "netspeed.title": "实时网速监控",
            "netspeed.upload": "上传速度",
            "netspeed.download": "下载速度",
            "netspeed.all_interfaces": "所有接口",
            "netspeed.realtime_chart": "实时图表",
            "netspeed.collecting": "采集数据中...",
            "netspeed.last_60s": "近 60 秒",
            "netspeed.interfaces": "网络接口",
            "netspeed.no_interfaces": "未检测到接口",
            "netspeed.traffic_stats": "流量统计",
            "netspeed.total_download": "总计下载",
            "netspeed.total_upload": "总计上传",
            "netspeed.total_traffic": "总计流量",
            "netspeed.traffic_trend": "流量趋势",
            "netspeed.tab.interfaces": "接口",
            "netspeed.tab.processes": "进程",
            "netspeed.process.name": "进程名",
            "netspeed.process.pid": "PID",
            "netspeed.process.connections": "连接",
            "netspeed.process.protocol": "协议",
            "netspeed.process.local": "本地",
            "netspeed.process.remote": "远程",
            "netspeed.process.state": "状态",
            "netspeed.process.port": "端口",
            "netspeed.process.kill": "终止",
            "netspeed.process.kill_confirm": "终止「%@」(PID %d)？",
            "netspeed.process.kill_success": "进程已终止",
            "netspeed.process.kill_failed": "终止失败",
            "netspeed.process.search": "搜索进程...",
            "netspeed.process.no_connections": "无活跃连接",
            "netspeed.process.refresh": "刷新",
            "netspeed.top_processes": "高带宽进程",
            "netspeed.process.speed": "实时带宽",
            
            // Logs (additions)
            "logs.title": "日志",
            "logs.empty": "暂无日志",
        ]
    ]
}
